#到货通知
notice_arrive:
  sms: "燕赵物流货到%s,货号%s,货款%s元,地址:%s,电话%s"
  phone: "您好,燕赵物流货物已到,稍后短信通知,请查收."
  sms_batch: "%s  燕赵物流货到%s,货号%s,货款%s元,地址:%s,电话%s\r\n"

#现金提款通知
notice_cash_payment_list:
  sms_batch: "%s  您的运单%s货款已到,请在周二或周六上午携带发货票 建行卡及有效证件到发货处领取.客服4006194448\r\n"
