#到货通知
notice_arrive:
  sms: "燕赵物流货到%s,运单号%s,货款合计:%s,地址:%s,电话:%s"
  phone: "您好,燕赵物流货物已到,稍后短信通知,请查收."
  sms_batch: "%s  燕赵物流货到%s,运单号%s,货款合计:%s,地址:%s,电话:%s"

#现金提款通知
notice_cash_payment_list:
  sms_batch: "%s  尊敬的客户:您的运单 %s 货款已到,请您在周二或周六上午携带发货票 银行卡及身份证到发货处领取.%s 联系电话:4006194448"
