#到货通知
notice_arrive:
  sms: 尊敬的客户:您的货物已到,货款%s 运费%s 合计%s 请及时提货,地址:%s %s %s
  phone: 尊敬的客户:您的货物已到,货款%s 运费%s 合计%s 请及时提货,地址:%s %s %s

#现金提款通知
notice_cash_payment_list:
  sms: 尊敬的客户:您的运单 %s 货款已到,请您在周二或周六上午携带发货票 银行卡及身份证到发货处领取.%s 4006194448/r/n
