require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ActLoadListsController do

  def mock_act_load_list(stubs={})
    @mock_act_load_list ||= mock_model(ActLoadList, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all act_load_lists as @act_load_lists" do
      ActLoadList.stub(:all) { [mock_act_load_list] }
      get :index
      assigns(:act_load_lists).should eq([mock_act_load_list])
    end
  end

  describe "GET show" do
    it "assigns the requested act_load_list as @act_load_list" do
      ActLoadList.stub(:find).with("37") { mock_act_load_list }
      get :show, :id => "37"
      assigns(:act_load_list).should be(mock_act_load_list)
    end
  end

  describe "GET new" do
    it "assigns a new act_load_list as @act_load_list" do
      ActLoadList.stub(:new) { mock_act_load_list }
      get :new
      assigns(:act_load_list).should be(mock_act_load_list)
    end
  end

  describe "GET edit" do
    it "assigns the requested act_load_list as @act_load_list" do
      ActLoadList.stub(:find).with("37") { mock_act_load_list }
      get :edit, :id => "37"
      assigns(:act_load_list).should be(mock_act_load_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created act_load_list as @act_load_list" do
        ActLoadList.stub(:new).with({'these' => 'params'}) { mock_act_load_list(:save => true) }
        post :create, :act_load_list => {'these' => 'params'}
        assigns(:act_load_list).should be(mock_act_load_list)
      end

      it "redirects to the created act_load_list" do
        ActLoadList.stub(:new) { mock_act_load_list(:save => true) }
        post :create, :act_load_list => {}
        response.should redirect_to(act_load_list_url(mock_act_load_list))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved act_load_list as @act_load_list" do
        ActLoadList.stub(:new).with({'these' => 'params'}) { mock_act_load_list(:save => false) }
        post :create, :act_load_list => {'these' => 'params'}
        assigns(:act_load_list).should be(mock_act_load_list)
      end

      it "re-renders the 'new' template" do
        ActLoadList.stub(:new) { mock_act_load_list(:save => false) }
        post :create, :act_load_list => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested act_load_list" do
        ActLoadList.stub(:find).with("37") { mock_act_load_list }
        mock_act_load_list.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :act_load_list => {'these' => 'params'}
      end

      it "assigns the requested act_load_list as @act_load_list" do
        ActLoadList.stub(:find) { mock_act_load_list(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:act_load_list).should be(mock_act_load_list)
      end

      it "redirects to the act_load_list" do
        ActLoadList.stub(:find) { mock_act_load_list(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(act_load_list_url(mock_act_load_list))
      end
    end

    describe "with invalid params" do
      it "assigns the act_load_list as @act_load_list" do
        ActLoadList.stub(:find) { mock_act_load_list(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:act_load_list).should be(mock_act_load_list)
      end

      it "re-renders the 'edit' template" do
        ActLoadList.stub(:find) { mock_act_load_list(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested act_load_list" do
      ActLoadList.stub(:find).with("37") { mock_act_load_list }
      mock_act_load_list.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the act_load_lists list" do
      ActLoadList.stub(:find) { mock_act_load_list }
      delete :destroy, :id => "1"
      response.should redirect_to(act_load_lists_url)
    end
  end

end
